bonds <- read.delim("bonds (1).txt",row.names = 1)
View(bonds)
head(bonds)
tail(bonds)
summary(bonds)
plot(bonds$CouponRate,bonds$BidPrice,main="Bid Prics vs Coupon Rate",xlab="CouponRate",ylab="BidPrice")
bondsmod <- lm(BidPrice~CouponRate,data = bonds)
abline(bondsmod)
plot(bondsmod$fitted.values,rstandard(bondsmod),main="Residual Plot",xlab="Predicted values of BidPrice",ylab="Residual values")
abline(h=2,lty=2)
abline(h=-2,lty=2)
identify(bondsmod$fitted.values,rstandard(bondsmod))
bonds_new=bonds[-c(4,13,34,35),]
bondsmod1= lm(bonds_new$BidPrice~bonds_new$CouponRate)
plot(bondsmod1$fitted.values,rstandard(bondsmod1),main="New Residual Plot",xlab="Predicted values of BidPrice",ylab="Residual values")
abline(h=2,lty=2)
abline(h=-2,lty=2)
abline(bondsmod1)
plot(bonds$BidPrice[-c(4,13,34,35)],bonds$CouponRate[-c(4,13,34,35)],main="New plot",xlab="CouponRate",ylab="BidPrice")
abline(bondsmod1)

